name: Cleanup
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    permissions: 
      actions: write
    steps:
      - name: Delete artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const {data} = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            if(!data.artifacts.length)
              return
            
            data.artifacts.forEach(artifact => {
              console.log(`Deleting artifact ${artifact.name},${artifact.id}`)
              github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              })
            })