name: BUILD

on: 
  push:
    branches:
      - 'ci/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    name: Build Unity
    runs-on: ubuntu-latest
    steps:
      - name: test script
        run: echo Hello World! 